#!/bin/bash

idirect="/etc/idir" && [[ ! -d $idirect ]] && mkdir $idirect

send_ID () {
          bot_retor="$LINE\n"
	  
          bot_retor+=" Cliente :『 ${callback_query_from_first_name} ${callback_query_from_last_name} 』\n"
	  bot_retor+=" Usuario :『  @${callback_query_from_username} 』\n"
          bot_retor+=" ➩   🆔 :『<code>${chatuser}</code>』 \n"
	  bot_retor+="$LINE\n"
          bot_retor+=" ESTA SOLICITANDO PERMISO PARA ACCEDER AL BOT-GEN\n"
          bot_retor+=" COMANDO PARA AÑADIR: /add\n EN EL SIGUIENTE ORDEN;\n"
          bot_retor+="   <code>${chatuser} | Dias</code> \n"
          bot_retor+="$LINE\n"
          bot_retor+=" VERIFIQUE SU TOKEN DE PAGO  ANTES DE LA AUTORIZACION\n"
          bot_retor+="$LINE\n"
		  msj_add "$(cat < ${CIDdir}/Admin-ID)"
    	bot_retorno="$LINE\n"
        bot_retorno+=" 🔰 𝚂𝚞 𝙸𝙳 【 <code>${chatuser}</code> 】 🔰\n"
        bot_retorno+="$LINE\n"
        bot_retorno+="Su ID fue enviado exitosamente a $(cat < /etc/ADM-db/resell)\n"
        bot_retorno+="$LINE\n"
        bot_retorno+="      ✅ ID enviado al Admin ✅\n"
        bot_retorno+="$LINE\n"
		bot_retorno+=" ENVIE SU TOKEN DE PAGO PARA SU AUTORIZACION\n"
		bot_retorno+="$LINE\n"
		msj_fun
}

myid_src () {
[[ $(cat ${CID}|grep "${chatuser}" ) = "" ]] && {
bot_retorno="──────────────────────\n"
          bot_retorno+="👋Hola [ @$message_from_username ] \n Tu ID no esta autorizado para poder usar el BOTGEN.\n"
           bot_retorno+="──────────────────────\n"
          bot_retorno+="🆔 : <code>${chatuser}</code> \n    ↗️ TOCA PARA COPIAR.\n"
          bot_retorno+="──────────────────────\n"
	  bot_retorno+="Para estar Autorizado, Realiza una Donacion o Adquiere una Membresia\n y envia tu Token de Donacion a $(cat < /etc/ADM-db/resell)\n"
          bot_retorno+="──────────────────────\n"
	  menu_printSN
} || {
#          bot_retor="$LINE\n"
#          bot_retor+=" Cliente :『 $message_from_first_name $message_from_last_name 』\n"
#          bot_retor+=" Usuario :『  @$message_from_username 』\n"
#          bot_retor+=" 🆔 : <code>${chatuser}</code> \n"
#          bot_retor+=" ESTA SOLICITANDO PERMISO PARA ACCEDER AL BOT-gen
          bot_retorno="================================\n"
          bot_retorno+="👋Hola @$message_from_username 】, Tu ID esta autorizado para poder usar el BOTGEN. \n"
          bot_retorno+="================================\n"
          bot_retorno+="Recuerda Evaluar El Proyecto y medir tu Experiencia en este SCRIPT\n.:Thanks you:.\n"
          bot_retorno+="================================\n"
msj_fun
}
}

deleteID_reply () {
ids=$(echo ${message_text[$id]} | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig')
idc=$(echo ${message_text[$id]} | awk '{print $3}' | sed -e 's/[^a-z0-9 -]//ig')
sed -i "${message_text[$id]}/d" ${CID}
bot_retorno="$LINE\n"
          bot_retorno+=" ID ELIMINADO EXITOSAMENTE!\n"
          bot_retorno+=" ID Eliminado: ${ids}\n"
          bot_retorno+="$LINE\n"

          bot_retor="  ✨ 𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘  nuevamente 𝚊𝚕 BOTGEN ✨\n"
          bot_retor+="$LINE\n"
  #     bot_retor+="👋Hola $message_from_first_name $message_from_last_name \n"
          bot_retor+="Desafortunadamente tu membresia ha finalizado.\n"
  #     bot_retor+="⌚ Hora Actual del Bot : ⌚\n"
          bot_retor+="Fecha de Corte : $idc \n"
          bot_retor+="Si tienes dudas, contacta con: \n  $(cat < /etc/ADM-db/resell)\n"
  #     bot_retor+="Recuerda adquirir creditos, o Realizar una Colaboracion\n $(cat < /etc/mpayu) \n"
  #     bot_retor+="Para mantener tu acceso al BotGen Recuerda Mostrar tu Token de Donacion o Compra\n"
          bot_retor+="$LINE\n"
      msj_fun
      msj_add ${ids}
      upfile_src
}

addID_reply () {
      [[ $(cat ${CID}|grep "${message_text[$id]}" ) = "" ]] && {
        #echo "/${message_text[$id]} | $(date '+%d-%m-%Y' -d " +$dias days")" >> $idirect/idtegm
        #cat $idirect/idtegm | awk '{print $1}' >> ${CID}
        #echo "/${message_text[$id]}" >> ${CID}
        ids=$(echo ${message_text[$id]} | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig')
        idc=$(echo ${message_text[$id]} | awk '{print $3}' | sed -e 's/[^a-z0-9 -]//ig')
        valid=$(date '%d-%m-%y%C+' -d " +$idc days")
        echo "/${ids} | $valid" >> ${CID}
          bot_retorno="  ✨ 𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘  $message_from_first_name  𝚊𝚕  BOTGEN.\n"
          bot_retorno+="$LINE\n"
          bot_retorno+="$(< ${CID})\n"
          bot_retorno+="$LINE\n"
          bot_retorno+="New ID: ${ids}\n"
          bot_retorno+="Valido Hasta : ${valid}\n"
          bot_retorno+="$LINE\n"
          bot_retorno+=" FORMATO DE INGRESO 0000000 | 1\n"
	  bot_retorno+="     ✅ID AGREGADO✅\n"
          bot_retorno+="$LINE\n"
unset i
for i in $(cat /etc/ADM-db/User-ID | awk '{print $3}'); do 
[[ $(date -d $i +%s) -ge $(date -d $(date '+%C%y-%m-%d') +%s) ]] || {
idlog=$(cat /etc/ADM-db/User-ID | grep "$i" | awk '{print $1}' | sed -e 's/[^a-z0-9 -]//ig')
sed -i "/${idlog}/d" /etc/ADM-db/User-ID
          bot_retor="  ✨ MENSAJE DE BOTGEN:\n"
          bot_retor+="Desafortunadamente tu membresia ha finalizado.\n"
          bot_retor+="Fecha de Corte : $i \n"
          bot_retor+="Si tienes dudas, contacta con: \n  $(cat < /etc/ADM-db/resell)\n"
          bot_retor+="$LINE\n"
#       bot_retor+="Recuerda adquirir creditos, o Realizar una Colaboracion\n $(cat < /etc/mpayu) \n"
#       bot_retor+="Para mantener tu acceso al BotGen Recuerda Mostrar tu Token de Donacion o Compra\n"
#       bot_retor+="$LINE\n"
msj_add ${idlog}
}
done
          bot_retor="  ✨ 𝙱𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘  nuevamente 𝚊𝚕  BOTGEN ✨\n"
          bot_retor+="$LINE\n"
          bot_retor+="El Administrador  $(cat < /etc/ADM-db/resell)  Te Autorizó.\n"
          bot_retor+="Autorización Valida Hasta : ${valid}\n"
          bot_retor+="Para GENERAR Key's usar el comando:\n/keygen\n"
          bot_retor+="Para MENU Digita el comando:\n/menu\n para actualizar el menu de comandos\n"
          bot_retor+="$LINE\n"
          bot_retor+="Recuerda adquirir creditos, o realizar una Colaboración:\n Billetera Movil\n"
          bot_retor+="Si tienes inconvenientes con el BOTGEN \n contactame: $(cat < /etc/ADM-db/resell) 📲\n"
          bot_retor+="Para mantener tu acceso al BOTGEN Recuerda Mostrar tu Token de Donacion o Compra.\n"
          bot_retor+="$LINE\n"
      msj_fun
      msj_add ${ids}
      upfile_src
    } || {
          bot_retorno="==== ERROR ====\n"
          bot_retorno+="Este ID ya esta Registrado\n"
	  bot_retorno+="  ❌ ID NO REGISTRADO ❌\n"
          bot_retorno+="$LINE\n"
      msj_fun
    }
}
